#!/bin/bash
echo "Explore web directories from terminal."

#CHECKING FOR DEPEDENCIES
printf "Checking dependencies.... "
dependencies=( "mpv" "curl" "fzf" "grep" "sed" )
for i in "${dependencies[@]}"
do
    [[ $(command -v "$i" 2>/dev/null) ]] || { echo -en "\n$i needs to be installed.";deps=1; }
done
[[ $deps -ne 1 ]] && echo "OK" || { echo -en "\nInstall dependencies for 100x better luck.\n";exit 1; }


printf "Enter web directory URL: "
read url

#check if url ends in "/"
url="$(echo "$url" | sed '/\/$/! s|$|/|' )"

function fetch () {

    #fetching directories from url to open in fzf
    link=$(curl -s "$url" | grep -Po "(?<=href=\")[^\?][^\"]*")
    link="$(urldecode "$link")"
    i="$(echo "$link" | fzf)"

    #takes link from fzf and attaches to url"
    url="${url}${i}"
    echo "Opening.... $url"
    case "$url" in
        *mp4|*mkv|*avi|*flac)
           echo "playing $url"
           setsid -f nohup mpv --fs "$url" > /dev/null 2>&1 ;;
        */)
           #recursion FTW!!
           url=`echo "$url" | sed "s/ /%20/g"`
           fetch
    esac

}

#make responses readable.
function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

fetch
